# Generated by Django 2.2.6 on 2019-10-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flexstar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientID', models.IntegerField(default=0)),
                ('twoDBarcode', models.IntegerField(default=0)),
                ('well_position', models.IntegerField(default=0)),
                ('dateImported', models.DateTimeField(verbose_name='date imported')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientID', models.IntegerField(default=0)),
                ('barcode', models.CharField(max_length=25)),
                ('dateImported', models.DateTimeField(verbose_name='date imported')),
            ],
        ),
    ]
