# Generated by Django 2.2.6 on 2019-10-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmidna', '0002_auto_20191023_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexstar',
            name='dateImported',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='hospitaldata',
            name='dateImported',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
